# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  solution: '**/*.sln'
  web: '**/WebAppPipeline/WebAppPipeline.csproj'
  lib: '**/Lib/Lib.csproj'
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  artifactName: 'WebAppRelease'

steps:

- task: NuGetToolInstaller@1
- task: DotNetCoreCLI@2
  displayName: Restore Lib Dependecies
  inputs:
    command: 'restore'
    projects: '$(lib)'
- task: DotNetCoreCLI@2
  displayName: Build Lib
  inputs:
    command: 'build'
    projects: '$(lib)'
- task: DotNetCoreCLI@2
  displayName: Restore Web Dependecies
  inputs:
    command: 'restore'
    projects: '$(web)'
- task: DotNetCoreCLI@2
  displayName: Build Web
  inputs:
    command: 'build'
    projects: '$(web)'
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactsStagingDirectory)'
    zipAfterPublish: true
- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactsStagingDirectory)'
    ArtifactName: '$(artifactName)'
     
