
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  lib: '**/Lib/Lib.csproj'
  unittest: '**/UnitTesting/UnitTesting.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(lib)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(unittest)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/WebAppPipeline/WebAppPipeline.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/FunctionalTesting/FunctionalTesting.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/IntegrationTesting/IntegrationTesting.csproj'
