# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubunto-latest'

variables:
  solution: '**/*.sln'
  web: ''
  lib: '**/Lib/Lib.csproj'
  unittests: ''
  functionaltests: ''
  integrationtest: ''
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  azuresubscrition: ''
  appName: ''
  containerregistryName: ''

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(lib)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(lib)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(unittests)'
