# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Lib/Lib.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/UnitTesting/UnitTesting.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/WebAppPipeline/WebAppPipeline.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/FunctionalTesting/FunctionalTesting.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/IntegrationTesting/IntegrationTesting.csproj'

